### ISSUE TITLE
"Note: this section needs to be updated to use t2-vm" is blocked

### ISSUE THREAD

**Issue by cflewis** [tessel/tessel-rust#10]
"Note: this section needs to be updated to use t2-vm" is blocked by https://github.com/tessel/t2-vm/issues/36 and https://github.com/tessel/t2-vm/issues/34

**Comment by johnnyman727** [comment]
Probably more accurately, that section should be rewritten to describe how to get [the Docker image](https://github.com/tessel/rust-compilation-server) up and running.

**Comment by cflewis** [comment]
Agreed, the Docker image is essentially a one liner for the majority of Linux flavors and all Mac users.

**Comment by tcr** [comment]
Going to close this, I think, as the issue was solved.
