### ISSUE TITLE
Can't seem to execute using OpenWRT linker

### ISSUE THREAD

**Issue by cflewis** [tessel/tessel-rust#12]
Using the scripts at https://github.com/japaric/rust-cross
and run at https://travis-ci.org/japaric/rust-cross/jobs/122683534

I was able to successfully build an executable using the OpenWRT linker:

```
[cflewis@aurora hello]$ file target/mipsel-unknown-linux-musl/debug/hello 
target/mipsel-unknown-linux-musl/debug/hello: ELF 32-bit LSB shared object, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-mipsel-sf.so.1, not stripped

[cflewis@aurora hello]$ ldd target/mipsel-unknown-linux-musl/debug/hello 
    not a dynamic executable

[cflewis@aurora hello]$ cat ~/.cargo/config 
[target.mipsel-unknown-linux-musl]
linker = "/home/cflewis/openwrt/toolchain-mipsel_24kc_gcc-5.3.0_musl-1.1.14/bin/mipsel-openwrt-linux-gcc"
```

However, after copying over the created executable from `cargo build --target=mipsel-unknown-linux-musl` all I get is this:

```
root@belle:~# ls -la
drwxr-xr-x    1 root     root             0 Jun 14 13:15 .
drwxr-xr-x    1 root     root             0 Jun 14 04:26 ..
-rwxr-xr-x    1 root     root        988864 Jun 15 23:04 hello

root@belle:~# ./hello
-ash: ./hello: not found
```

I'm not building things right somehow, but this seems to be the right way to go about a Hello World from a Linux platform:
- Get `rustup`
- Install stable Rust
- Download OpenWRT SDK and untar it
- Add the linker to the cargo config
- `cargo new hello --bin; cargo build --target=[foo]`
- `scp` to Tessel
- `ssh` to Tessel to execute

What am I doing wrong?

**Comment by johnnyman727** [comment]
Closing this since @cflewis reported that he got [the docker image](https://github.com/tessel/rust-compilation-server) working without a problem.
