### ISSUE TITLE
Library claims LED brightness files don't exist on Tessel

### ISSUE THREAD

**Issue by johnnyman727** [tessel/tessel-rust#5]
When I cross-compile this library for Tessel and run the hello world example, I get the following error when [I create a new Tessel](https://github.com/tessel/tessel-rust/blob/master/src/main.rs#L14):

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No suc
h file or directory" } }', src/libcore/result.rs:738
```

It is being thrown from [this line](https://github.com/tessel/tessel-rust/blob/master/src/lib.rs#L94). I have confirmed that the expected path does exist on Tessel so I'm not sure what to look at next.

**Comment by johnnyman727** [comment]
Here is the binary if anyone wants to run it themselves on their T2.

**Comment by kevinmehall** [comment]
`/sys/devices`, not `/sys/device`

**Comment by johnnyman727** [comment]
I owe you a six pack of root beer for such a dumb question. 🍻
