### ISSUE TITLE
Readme needs an update

### ISSUE THREAD

**Issue by Frijol** [tessel/tessel-rust#7]
- [x] GPS module is listed under USB
- [x] Setup step 1 should probably link to Rust's own install recommendations
- [x] Switch from Vagrant to a native compiler?
- [x] Contact shouldn't link to Ken's email
- [x] Contact should direct people to the rust channel on slack
- [x] Read over the whole thing for relevance

**Comment by johnnyman727** [comment]
I'm going to put this off until we have a better consensus on how to do deployments (ie a remote server or using `rustup`).

**Comment by cflewis** [comment]
Where is this deployments discussion taking place? All the Vagrant stuff seems like a pretty harsh learning curve :(

**Comment by cflewis** [comment]
The README does not currently work. The rust libraries are different versions I think  (the Readme alludes to a linker issue and handwaves a "do it yourself" which isn't helpful :/ )

I'm going to try following a workflow which seems to be building for OpenWRT on Travis CI tonight, but as it stands, I think it's a bit premature for the Tessel Web site to advertise rust. It's not possible for the target Tessel audience to use it right now.

**Comment by johnnyman727** [comment]
For the sake of anyone watching this issue, I recommend using [this Docker build](https://github.com/tessel/rust-compilation-server) instead of trying to get Vagrant linking working.

**Comment by Frijol** [comment]
@johnnyman727 should this be closed, or relabeled?
